language: go
go:
  - 1.6.2
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v github.com/tools/godep
script:  
  - go vet ./...
  - bin/test
branches:
  only:
  - master
